PRACTISE NUMPY
[100_Numpy_exercises.ipynb](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)

In [2]:
import numpy as np
array1=np.array([[1,2,3,4],[4,5,6,7]])
print(array1)

[[1 2 3 4]
 [4 5 6 7]]


In [8]:
array2=(np.arange(0,11,1)*2)
print(np.trim_zeros(array2))

[ 2  4  6  8 10 12 14 16 18 20]


In [12]:
array_zero=np.zeros((2,2))
array_ones=np.ones((2,2))
array_const=np.full((2,2),7)
print(array_zero)
print(array_ones)
print(array_const)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]


In [ ]:
array1=np.array([1,2,3,4])
print(np.shape(array1))                             # Retrieves the Total nos of rows and Columns in the array
print(np.ndim(array1))                              # Tells the dimension of the array
print(np.size(array1))                              # Tells the length of the array
print(array1.dtype)                                 # Tells the type of input in the array

(4,)
1
4
int64


In [ ]:
array_demo=np.array([1,2,3,4,5,6,7,8])
reshaped=array_demo.reshape(4,2)                 #Used to reshape the array for example Array to matrix
print(reshaped)

print(reshaped.flatten())                        #Used to flatten a matrix
print(reshaped.ravel())                          #Used to Faltten a matrix (It is memory Efficient)
print(reshaped.T)                                #Used to produce Transpose of an Array

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
import numpy as np
demo=[[1,2,3],[4,5,6],[7,8,9]]
array1=np.array(demo)
print(array1[2,2])                      #To get a particular Element
print(array1[0])                        #To get a particular Row
print(array1[:,0])                      #To get a particular Column

9
[1 2 3]
[1 4 7]


In [38]:
demo=[[7,8,9],[1,2,3],[6,4,5]]
print(np.sort(demo[1]))             #sort a particular row of the matrix
print(np.sort(demo,axis=0))         #sort a 2D matrix as per columns
print(np.sort(demo,axis=1))         #sort a 2D matrix as per rows

[1 2 3]
[[1 2 3]
 [6 4 5]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [ ]:
array_elements=np.array([1,2,3,4,5,6,7,8,9,10])                             #Use of masking
process= array_elements%2==0
print(array_elements[process])

3


In [ ]:
demo_array=np.where(array_elements%2==0,True,False)      #use of np.where
print(demo_array)

[False  True False  True False  True False  True False  True]


In [48]:
add_arrray_1=np.array([1,2,3])
add_array_2=np.array([4,5,6])

print(add_arrray_1+add_array_2)                                     # Used to add 2 arrays
final_array=np.concatenate((add_arrray_1,add_array_2))              # Used to concat 2 arrays

print(f"Compitiable: {np.shape(add_array_2)==np.shape(final_array)}")

[5 7 9]
Compitiable: False


In [ ]:
array_original=np.array([[1,2,3],[4,5,6]])
arrray_to_be_added_row=np.array([[7,8,9]])
arrray_to_be_added_column=np.array([[11,12,13],[14,15,16],[17,118,19]])
new_array_row=np.vstack((array_original,arrray_to_be_added_row))                #np.vstack() used to add rows to the array
new_array_column=np.hstack((new_array_row,arrray_to_be_added_column))           #np.hstack()  used to add new columns to the array

print(array_original,'\n')
print(new_array_row,'\n')
print(new_array_column,'\n')

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[  1   2   3  11  12  13]
 [  4   5   6  14  15  16]
 [  7   8   9  17 118  19]] 



In [ ]:
array=np.array([[1,2,3],[4,5,6]])
array_modified=np.delete(array,1,axis=0)                # Used to Delete The Array
print(array_modified)

[[1 2 3]]


In [ ]:
#We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)                

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
import numpy as np
demo_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(demo_array,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
